routes/web.php
<?php

use App\Http\Controllers\AccessoriesController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AppController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\HomeSliderController;
use App\Http\Controllers\HuggingFaceController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\SyncController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/',[AdminController::class, 'index'])->name('admin');
    
    Route::get('/blog/list', [BlogController::class, 'list'])->name('blog.list');
    Route::resource('blog', BlogController::class)->except(['index', 'show']);
    
    Route::resource('dates', DateController::class);
    
    Route::get('/date-from',[AttendanceController::class, 'dateFrom'])->name('date-from');
    Route::post('/date-from',[AttendanceController::class, 'dateFromStore']);

    Route::get('/cache', [AccessoriesController::class, 'cache']);
    Route::get('/clear', [AccessoriesController::class, 'clearCache']);

    Route::get('/home-sliders/list', [HomeSliderController::class, 'list'])->name('home-sliders.list');
    Route::resource('home-sliders', HomeSliderController::class);
    Route::resource('images', ImageController::class);
    Route::resource('notices', NoticeController::class)->except(['show']);
    Route::get('/notices/list', [NoticeController::class, 'list'])->name('notices.list');

    Route::get('/results/export', [ResultController::class, 'export'])->name('results.export');
    Route::post('/results/download', [ResultController::class, 'download'])->name('results.download');
    Route::get('/results/import', [ResultController::class, 'import'])->name('results.import');
    Route::get('/results/list', [ResultController::class, 'list'])->name('results.list');
    Route::post('/results/upload', [ResultController::class, 'upload'])->name('results.upload');
    Route::resource('results', ResultController::class)->except(['index']);

    Route::get('/routines/list', [RoutineController::class, 'list'])->name('routines.list');
    Route::resource('routines', RoutineController::class)->except(['index']);

    Route::put('/users/{id}/meta', [UserController::class, 'meta'])->name('users.meta');
    Route::get('/users/import', [UserController::class, 'import'])->name('users.import');
    Route::post('/users/import', [UserController::class, 'upload'])->name('users.upload');
    Route::get('/users/list', [UserController::class, 'list'])->name('users.list');
});
Route::middleware('cache.headers:public;max_age=300;etag')->group(function () {
    Route::resource('attendances', AttendanceController::class)->except(['show']);
    Route::get('/attendances/{hsc}/{roll}/{name?}', [AttendanceController::class, 'show'])->name('attendances.show');

    Route::get('/facebook/login', [FacebookController::class, 'login'])->name('facebook.login');
    Route::get('/facebook/callback', [FacebookController::class, 'callback'])->name('facebook.callback');
    Route::get('/facebook/stories', [FacebookController::class, 'fetchStories'])->name('facebook.stories');

    Route::get('/wall', [AppController::class, 'wall'])->name('app.wall');
});
Route::middleware('cache.headers:public;max_age=604800;etag')->group(function () {
    Route::get('/', [AppController::class, 'home'])->name('app.home');
    Route::get('/about', [AppController::class, 'about'])->name('app.about');
    Route::get('/academic-rules', [AppController::class, 'academicRules'])->name('academic-rules');
    Route::get('blog', [BlogController::class, 'index'])->name('blog.index');
    Route::get('/blog/{id}/{slug?}', [BlogController::class, 'show'])->name('blog.show');
    Route::get('/c', [AppController::class, 'c'])->name('app.c');
    Route::get('/cache', [AccessoriesController::class, 'cache'])->name('cache');
    Route::resource('comments', CommentController::class);
    Route::get('/contact', [AppController::class, 'contact'])->name('app.contact');
    Route::get('/falling-letter', [GameController::class, 'fallingLetter'])->name('app.falling-letter');
    Route::get('/image/{w}/{h}/{filename}', [ImageController::class, 'showResizedImage']);
    Route::resource('likes', LikeController::class);
    Route::get('/principals-message', [AppController::class, 'principal'])->name('app.principal');
    Route::get('/privacy-policy', [AppController::class, 'privacyPolicy'])->name('app.privacy-policy');
    Route::get('/sitemap.xml', [AccessoriesController::class, 'sitemap'])->name('sitemap');
    Route::get('/staffs', [UserController::class, 'staffs'])->name('users.staffs');
    Route::get('/students', [UserController::class, 'students'])->name('users.students');
    Route::get('/teachers', [UserController::class, 'teachers'])->name('users.teachers');
    Route::get('/vice-principals-message', [AppController::class, 'vice'])->name('app.vice');
    /*
    * Overwriting the controllers in admin group
    */
    Route::resource('users', UserController::class)->except('show');
    Route::resource('status', PostController::class);
    Route::get('/notices/{id}/{slug?}', [NoticeController::class, 'show'])->name('notices.show');
    Route::get('/results', [ResultController::class, 'index'])->name('results.index');
    Route::get('/routines', [RoutineController::class, 'index'])->name('routines.index');
});

require __DIR__.'/auth.php';
Route::get('/clear-cache', [AccessoriesController::class, 'clearCache'])->name('clear-cache');
Route::get('/generate-text', [HuggingFaceController::class, 'chat']);
Route::get('/sync', [SyncController::class, 'sync']);


Route::middleware('cache.headers:public;max_age=60;etag')->group(function () {
    Route::get('/users/{id}/{name?}', [UserController::class, 'show'])->name('users.show');
});

resources/views/layouts/backend/footer.blade.php
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    {{ csrf_field() }}
</form>
<form id="delete-form" action="#" method="POST" style="display: none;" onsubmit="return confirm('Are you sure you want to delete?');">
    {{ csrf_field() }}
    {{ method_field('DELETE') }}
    <input type="submit" name="submit" />
</form>

resources/views/layouts/backend/header.blade.php
  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="{{ url('images/logo.png') }}" alt="AdminLTELogo" height="60" width="60">
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{ route('admin') }}" class="nav-link">Dashboard</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/images/profile/{{ $user->photo ?? 'avatar.webp' }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/images/profile/{{ $user->photo ?? 'avatar.webp' }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/images/profile/{{ $user->photo ?? 'avatar.webp' }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/layouts/backend/leftbar.blade.php
 <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="{{ url('images/logo.png') }}" alt="ICT for Today Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">{{ config("app.short_name") }}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ url('images/profile/'.$user->photo ?? 'avatar.webp') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{{ route('users.show', $user->id) }}" class="d-block">{{ $user->name ?? '' }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item {{ Request::is('admin/routines/list') ? 'menu-open' : '' }}">
            <a href="{{ route('routines.list') }}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Routines
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
          <li class="nav-item {{ Request::is('admin/home-sliders*') ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Home Slider
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('home-sliders.list') }}" class="nav-link {{ Request::is('admin/home-sliders/list') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Sliders</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('home-sliders.create') }}" class="nav-link {{ Request::is('admin/home-sliders/create') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add New</p>
                </a>
              </li>
            </ul>
          </li>
          
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-envelope"></i>
              <p>
                SMS
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="pages/mailbox/mailbox.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Settings</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/mailbox/compose.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Send</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item {{ Request::is('admin/users*') ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-user"></i>
              <p>
                Users
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('users.list') }}" class="nav-link {{ Request::is('admin/users-list') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>User List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('users.import') }}" class="nav-link {{ Request::is('admin/users/import') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Import</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon {{ Request::is('admin/date-from*') ? 'menu-open' : '' }} far fa-clock"></i>
              <p>
                Attendance
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('date-from') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Date from</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/mailbox/compose.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Import</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item {{ Request::is('admin/notices*') ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-bell"></i>
              <p>
                Notice
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('notices.list') }}" class="nav-link {{ Request::is('admin/notices/list') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All Notices</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('notices.create') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add New</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item {{ Request::is('admin/results*') ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-graduation-cap"></i>
              <p>
                Result
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('results.list') }}" class="nav-link {{ Request::is('admin/results-list') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Result List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('results.import') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Import</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('results.export') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Export</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item {{ Request::is('admin/dates*') ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fa fa-calendar"></i>
              <p>
                Date
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{ route('dates.index') }}" class="nav-link {{ Request::is('admin/dates') ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>All dates</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('dates.create') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Add New</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>