routes/web.php
<?php

use App\Http\Controllers\AccessoriesController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AppController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\HomeSliderController;
use App\Http\Controllers\HuggingFaceController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\SyncController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/',[AdminController::class, 'index'])->name('admin');
    
    Route::get('/blog/list', [BlogController::class, 'list'])->name('blog.list');
    Route::resource('blog', BlogController::class)->except(['index', 'show']);
    
    Route::resource('dates', DateController::class);
    
    Route::get('/date-from',[AttendanceController::class, 'dateFrom'])->name('date-from');
    Route::post('/date-from',[AttendanceController::class, 'dateFromStore']);

    Route::get('/cache', [AccessoriesController::class, 'cache']);
    Route::get('/clear', [AccessoriesController::class, 'clearCache']);

    Route::get('/home-sliders/list', [HomeSliderController::class, 'list'])->name('home-sliders.list');
    Route::resource('home-sliders', HomeSliderController::class);
    Route::resource('images', ImageController::class);
    Route::resource('notices', NoticeController::class)->except(['show']);
    Route::get('/notices/list', [NoticeController::class, 'list'])->name('notices.list');

    Route::get('/results/export', [ResultController::class, 'export'])->name('results.export');
    Route::post('/results/download', [ResultController::class, 'download'])->name('results.download');
    Route::get('/results/import', [ResultController::class, 'import'])->name('results.import');
    Route::get('/results/list', [ResultController::class, 'list'])->name('results.list');
    Route::post('/results/upload', [ResultController::class, 'upload'])->name('results.upload');
    Route::resource('results', ResultController::class)->except(['index']);

    Route::get('/routines/list', [RoutineController::class, 'list'])->name('routines.list');
    Route::resource('routines', RoutineController::class)->except(['index']);

    Route::put('/users/{id}/meta', [UserController::class, 'meta'])->name('users.meta');
    Route::get('/users/import', [UserController::class, 'import'])->name('users.import');
    Route::post('/users/import', [UserController::class, 'upload'])->name('users.upload');
    Route::get('/users/list', [UserController::class, 'list'])->name('users.list');
});
Route::middleware('cache.headers:public;max_age=300;etag')->group(function () {
    Route::resource('attendances', AttendanceController::class)->except(['show']);
    Route::get('/attendances/{hsc}/{roll}/{name?}', [AttendanceController::class, 'show'])->name('attendances.show');

    Route::get('/facebook/login', [FacebookController::class, 'login'])->name('facebook.login');
    Route::get('/facebook/callback', [FacebookController::class, 'callback'])->name('facebook.callback');
    Route::get('/facebook/stories', [FacebookController::class, 'fetchStories'])->name('facebook.stories');

    Route::get('/wall', [AppController::class, 'wall'])->name('app.wall');
});
Route::middleware('cache.headers:public;max_age=604800;etag')->group(function () {
    Route::get('/', [AppController::class, 'home'])->name('app.home');
    Route::get('/about', [AppController::class, 'about'])->name('app.about');
    Route::get('/academic-rules', [AppController::class, 'academicRules'])->name('academic-rules');
    Route::get('blog', [BlogController::class, 'index'])->name('blog.index');
    Route::get('/blog/{id}/{slug?}', [BlogController::class, 'show'])->name('blog.show');
    Route::get('/c', [AppController::class, 'c'])->name('app.c');
    Route::get('/cache', [AccessoriesController::class, 'cache'])->name('cache');
    Route::resource('comments', CommentController::class);
    Route::get('/contact', [AppController::class, 'contact'])->name('app.contact');
    Route::get('/falling-letter', [GameController::class, 'fallingLetter'])->name('app.falling-letter');
    Route::get('/image/{w}/{h}/{filename}', [ImageController::class, 'showResizedImage']);
    Route::resource('likes', LikeController::class);
    Route::get('/principals-message', [AppController::class, 'principal'])->name('app.principal');
    Route::get('/privacy-policy', [AppController::class, 'privacyPolicy'])->name('app.privacy-policy');
    Route::get('/sitemap.xml', [AccessoriesController::class, 'sitemap'])->name('sitemap');
    Route::get('/staffs', [UserController::class, 'staffs'])->name('users.staffs');
    Route::get('/students', [UserController::class, 'students'])->name('users.students');
    Route::get('/teachers', [UserController::class, 'teachers'])->name('users.teachers');
    Route::get('/vice-principals-message', [AppController::class, 'vice'])->name('app.vice');
    /*
    * Overwriting the controllers in admin group
    */
    Route::resource('users', UserController::class)->except('show');
    Route::resource('status', PostController::class);
    Route::get('/notices/{id}/{slug?}', [NoticeController::class, 'show'])->name('notices.show');
    Route::get('/results', [ResultController::class, 'index'])->name('results.index');
    Route::get('/routines', [RoutineController::class, 'index'])->name('routines.index');
});

require __DIR__.'/auth.php';
Route::get('/clear-cache', [AccessoriesController::class, 'clearCache'])->name('clear-cache');
Route::get('/generate-text', [HuggingFaceController::class, 'chat']);
Route::get('/sync', [SyncController::class, 'sync']);


Route::middleware('cache.headers:public;max_age=60;etag')->group(function () {
    Route::get('/users/{id}/{name?}', [UserController::class, 'show'])->name('users.show');
});

app/Http/Controllers/HomeSliderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Image2WebpController;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\File;

class HomeSliderController extends Controller {
    protected $converter;
    public function __construct() {
        $this->middleware('admin');
        $this->converter = new Image2WebpController();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $posts = Post::orderBy('id', 'desc')->paginate(10);
        return view('home-sliders.index', compact('posts'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function list() {
        $posts = Post::where('type', 'home-slider')->latest()->get();
        return view('home-sliders.list', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('home-sliders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $data = $request->except('_token', '_method');
        $file = $request->file('link');
        if ($file) {
            $destination_path = 'posts';
            $only_name = time() . '-image'; 
            $new_name = $only_name . '.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $this->converter->convert($destination_path.'/'.$new_name, 1000, 562);
            $data['link'] = $only_name . '.webp';
        }
        $data['type'] = 'home-slider';
        $data['user_id'] = auth()->id();
        $post = Post::create($data);
        $this->recache();
        return redirect(route('home-sliders.list'))->with('message', 'Slider added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $post = Post::find($id);
        return view('home-sliders.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $post = Post::find($id);
        return view('home-sliders.create', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $data = $request->except('_token', '_method');
        $post = Post::find($id);
        $directory = 'posts/';
        $file = $request->file('link');
        if ($file) {
            $destination_path = 'posts';
            $only_name = time() . '-image'; 
            $new_name = $only_name . '.' . $file->getClientOriginalExtension();
            $file->move($destination_path, $new_name);
            $this->converter->convert($destination_path.'/'.$new_name, 1000, 562);
            $data['link'] = $only_name . '.webp';
            File::delete($directory . $post->link);
        }
        $post->update($data);
        $this->recache();
        return redirect(route('home-sliders.list'))->with('message', 'Post updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $post = Post::find($id);
        $directory = 'posts/';
        File::delete($directory . $post->pdf);
        $post->delete();
        return redirect()->back()->with('message', 'Slider has been deleted');
    }
    private function recache() {
        Cache::forget('home');
        $data['slides'] = Post::where('type', 'home-slider')->latest()->get();
        $data['movings'] = Post::where('type', 'notice')->with('metas')->latest()->get();
        $data['principal'] = User::where('role', config('auth.role')['principal'])->with('userMeta')->where('status', 1)->first();
        $data['vice'] = User::where('role', config('auth.role')['vice'])->with('userMeta')->where('status', 1)->first();
        Cache::put('home', $data);
    }
}

resources/views/home-sliders/create.blade.php
@extends('layouts.backend')
@section('title')
{{ __(isset($post)?'Update post':'Create post') }}
@endsection
@section('content')
<div class="content">
    <div class="container-fluid">
        @if(session()->has('message'))
        <div class="alert alert-warning">
            {{ session()->get('message') }}
        </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="card card-light">
                    <div class="card-header with-border">
                        <h3 class="card-title"><i class="fa fa-edit"></i> {{ __(isset($post)?'Update Slider':'Add Slider') }}</h3>
                        <div class="card-tools float-right">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fa fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row pt-2">
                            <div class="col-12"><!--left col-->
                                <form action="@if(isset($post)) {{ route('home-sliders.update', $post->id) }} @else {{ route('home-sliders.store') }} @endif" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if(isset($post))
                                    @method('PUT')
                                    @endif
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input id="title" type="text" class="form-control" name="title" value="{{ $post->title ?? '' }}" placeholder="Tittle" title="Enter title" />
                                    </div>
                                    <div class="row">
                                        <div class="col-6 form-group">
                                            <label for="link">Image (1000x562)</label>
                                            <input type="file" id="link" name="link" class="form-control bg-theme text-white" accept="image/*" value="Upload image" />
                                            <div class="valid-feedback">Valid.</div>
                                            <div class="invalid-feedback">Please fill out this field.</div>
                                        </div>
                                        <div class="col-6 form-group">
                                            <a href="{{ asset('/posts') }}/{{ $post->link ?? 'placeholder.webp' }}" class="btn btn-link fa fa-download" download> {{ $post->link ?? '' }}</a>
                                        </div>
                                    </div>
                                    <div class="form-group mt-3">
                                        <button class="btn btn-success btn-theme" type="submit">{{ __(isset($post)?'Update':'Save') }}</button>
                                    </div>
                                </form>
                            </div><!--/col-9-->
                        </div><!--/row-->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home-sliders/index.blade.php
@extends('layouts.common')
@section('title')
{{ __('Home') }}
@endsection
@section('content')
<div class="row">
    <div class="col-sm-0 col-lg-2"></div>
    <div class="col-sm-12 col-lg-6 bg-white py-5">
        @foreach($posts as $post)
        <div class="row my-2">
            <div class="col-12 col-md-6 col-lg-4"><img src="{{ url('/') }}/assets/notices/{{ $post->thumbnail }}" class="img-thumbnail" /></div>
            <div class="col-12 col-md-6 col-lg-8">
                <h4><a href="{{ route('notices.show', $post->id) }}">{{ $post->title }}</a></h4>
                <hr/>
                <span class="text-secondary">By {{ $post->user->name }}</span> <span class="float-right">At {{ $post->created_at->format('jS M Y') }}</span>
                <hr/>
                <div class="text-justify">{!! excerpt($post->body, 400) !!} <a class="btn btn-link" href="{{ route('notices.show', $post->id) }}">...more</a></div>
            </div>
        </div>
        @endforeach
    </div>
    <div class="col-sm-0 col-lg-2 bg-white py-5">
        <div class="card">
            <div class="card-header">Categories</div>
            <div class="card-body">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="btn btn-link" href="{{ route('notices.index') }}">All Posts</a></li>
                    @foreach($categories as $category)
                    <li class="nav-item"><a class="btn btn-link" href="{{ route('notices.index') }}?category={{ $category->id }}">{{ $category->name }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="pagination-nav d-flex justify-content-center">
            {{ $posts->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/home-sliders/list.blade.php
@extends('layouts.backend')
@section('title')
{{ __('All Notices') }}
@endsection
@section('content')
<div class="content">
    <div class="container-fluid">
        @if(session()->has('message'))
        <div class="alert alert-warning">
            {{ session()->get('message') }}
        </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="card card-light">
                    <div class="card-header with-border">
                        <h3 class="card-title"><i class="nav-icon far fa-image mr-1"></i> {{ __('Slider List') }}</h3>
                        <div class="card-tools float-right">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fa fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="dataTables" class="display nowrap" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Posted at</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->title }}</td>
                                    <td>{{ $post->created_at->format('jS M Y') }}</td>
                                    <td><a href="{{ route('home-sliders.edit', $post->id) }}" class="text-success fa fa-edit"></a></td>
                                    <td><a href="{{ route('home-sliders.destroy', $post->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form').action = this.href; document.getElementById('delete-form').submit.click();" class="text-danger fa fa-trash"></button></td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Noticeed at</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('style')
<!-- dataTables plugin -->
<link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet" media="all"/>
<link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet" media="screen">
<link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet" media="all"/>
<!-- /dataTables plugin -->
@endsection
@section('script')
<!---dataTables plugin JavaScript -->
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="{{ asset('js/dataTables.js') }}"></script>
<!--/dataTables plugin JavaScript -->
@endsection

resources/views/home-sliders/show.blade.php
@extends('layouts.app')
@section('title')
{{ $post->title ?? '' }}
@endsection
@section('content')
<div class="container mx-auto min-h-screen">
    <div class="grid lg:grid-cols-[auto_1fr_auto] py-3">
        <div class="hidden lg:block">
            @include('layouts.info')
        </div>
        <div class="lg:px-3">
            <h1 class="">{{  $post->title ?? '' }}</h1>
            <div class="mb-3">
                <p class="text-gray-500 text-sm">Posted at: {{ $post->created_at->format('jS M Y') }}</p>
            </div>
            <div class="mb-3">
                {{  $post->body ?? '' }}
            </div>
            <object data="/posts/{{ $post->link }}" type="application/pdf" width="600" height="500" class="w-full overflow-hidden border-4">
                <p class="bg-theme-light p-3 rounded"><a class="underline" href="/posts/{{ $post->link }}" download>{{ $post->title ?? 'Download' }}</a></p>
                <embed src="/posts/{{ $post->link }}" width="100%" height="600px"/>
            </object>
        </div>
        <div class="hidden lg:block">
            @include('layouts.subject')
        </div>
    </div>
</div>
@endsection