routes/web.php
<?php

use App\Http\Controllers\AccessoriesController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AppController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\DateController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\HomeSliderController;
use App\Http\Controllers\HuggingFaceController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\GameController;
use App\Http\Controllers\NoticeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ResultController;
use App\Http\Controllers\RoutineController;
use App\Http\Controllers\SyncController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::group(['prefix' => 'admin', 'middleware' => 'admin'], function () {
    Route::get('/',[AdminController::class, 'index'])->name('admin');
    
    Route::get('/blog/list', [BlogController::class, 'list'])->name('blog.list');
    Route::resource('blog', BlogController::class)->except(['index', 'show']);
    
    Route::resource('dates', DateController::class);
    
    Route::get('/date-from',[AttendanceController::class, 'dateFrom'])->name('date-from');
    Route::post('/date-from',[AttendanceController::class, 'dateFromStore']);

    Route::get('/cache', [AccessoriesController::class, 'cache']);
    Route::get('/clear', [AccessoriesController::class, 'clearCache']);

    Route::get('/home-sliders/list', [HomeSliderController::class, 'list'])->name('home-sliders.list');
    Route::resource('home-sliders', HomeSliderController::class);
    Route::resource('images', ImageController::class);
    Route::resource('notices', NoticeController::class)->except(['show']);
    Route::get('/notices/list', [NoticeController::class, 'list'])->name('notices.list');

    Route::get('/results/export', [ResultController::class, 'export'])->name('results.export');
    Route::post('/results/download', [ResultController::class, 'download'])->name('results.download');
    Route::get('/results/import', [ResultController::class, 'import'])->name('results.import');
    Route::get('/results/list', [ResultController::class, 'list'])->name('results.list');
    Route::post('/results/upload', [ResultController::class, 'upload'])->name('results.upload');
    Route::resource('results', ResultController::class)->except(['index']);

    Route::get('/routines/list', [RoutineController::class, 'list'])->name('routines.list');
    Route::resource('routines', RoutineController::class)->except(['index']);

    Route::put('/users/{id}/meta', [UserController::class, 'meta'])->name('users.meta');
    Route::get('/users/import', [UserController::class, 'import'])->name('users.import');
    Route::post('/users/import', [UserController::class, 'upload'])->name('users.upload');
    Route::get('/users/list', [UserController::class, 'list'])->name('users.list');
});
Route::middleware('cache.headers:public;max_age=300;etag')->group(function () {
    Route::resource('attendances', AttendanceController::class)->except(['show']);
    Route::get('/attendances/{hsc}/{roll}/{name?}', [AttendanceController::class, 'show'])->name('attendances.show');

    Route::get('/facebook/login', [FacebookController::class, 'login'])->name('facebook.login');
    Route::get('/facebook/callback', [FacebookController::class, 'callback'])->name('facebook.callback');
    Route::get('/facebook/stories', [FacebookController::class, 'fetchStories'])->name('facebook.stories');

    Route::get('/wall', [AppController::class, 'wall'])->name('app.wall');
});
Route::middleware('cache.headers:public;max_age=604800;etag')->group(function () {
    Route::get('/', [AppController::class, 'home'])->name('app.home');
    Route::get('/about', [AppController::class, 'about'])->name('app.about');
    Route::get('/academic-rules', [AppController::class, 'academicRules'])->name('academic-rules');
    Route::get('blog', [BlogController::class, 'index'])->name('blog.index');
    Route::get('/blog/{id}/{slug?}', [BlogController::class, 'show'])->name('blog.show');
    Route::get('/c', [AppController::class, 'c'])->name('app.c');
    Route::get('/cache', [AccessoriesController::class, 'cache'])->name('cache');
    Route::resource('comments', CommentController::class);
    Route::get('/contact', [AppController::class, 'contact'])->name('app.contact');
    Route::get('/falling-letter', [GameController::class, 'fallingLetter'])->name('app.falling-letter');
    Route::get('/image/{w}/{h}/{filename}', [ImageController::class, 'showResizedImage']);
    Route::resource('likes', LikeController::class);
    Route::get('/principals-message', [AppController::class, 'principal'])->name('app.principal');
    Route::get('/privacy-policy', [AppController::class, 'privacyPolicy'])->name('app.privacy-policy');
    Route::get('/sitemap.xml', [AccessoriesController::class, 'sitemap'])->name('sitemap');
    Route::get('/staffs', [UserController::class, 'staffs'])->name('users.staffs');
    Route::get('/students', [UserController::class, 'students'])->name('users.students');
    Route::get('/teachers', [UserController::class, 'teachers'])->name('users.teachers');
    Route::get('/vice-principals-message', [AppController::class, 'vice'])->name('app.vice');
    /*
    * Overwriting the controllers in admin group
    */
    Route::resource('users', UserController::class)->except('show');
    Route::resource('status', PostController::class);
    Route::get('/notices/{id}/{slug?}', [NoticeController::class, 'show'])->name('notices.show');
    Route::get('/results', [ResultController::class, 'index'])->name('results.index');
    Route::get('/routines', [RoutineController::class, 'index'])->name('routines.index');
});

require __DIR__.'/auth.php';
Route::get('/clear-cache', [AccessoriesController::class, 'clearCache'])->name('clear-cache');
Route::get('/generate-text', [HuggingFaceController::class, 'chat']);
Route::get('/sync', [SyncController::class, 'sync']);


Route::middleware('cache.headers:public;max_age=60;etag')->group(function () {
    Route::get('/users/{id}/{name?}', [UserController::class, 'show'])->name('users.show');
});

app/Models/Date.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Date extends Model {
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'note',
        'status',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    public $timestamps = false;
}

app/Http/Controllers/DateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Models\Date;

class DateController extends Controller {
    public function __construct() {
        $this->middleware('admin', ['except' => [
            'show'
        ]]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $posts = Date::all();
        return view('dates.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('dates.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $data = $request->except('_token', '_method');
        if(isset($data['status'])) {
            $data["status"] = 1;
        } else {
            $data["status"] = 0;
        }
        Date::create($data);
        return redirect(route('dates.index'))->with('message', 'Date created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $post = Date::find($id);
        return view('dates.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $post = Date::find($id);
        return view('dates.create', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $data = $request->except('_token', '_method');
        if(isset($data['status'])) {
            $data["status"] = 1;
        } else {
            $data["status"] = 0;
        }
        $post = Date::find($id);
        $post->update($data);
        return redirect(route('dates.index'))->with('message', 'Date updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        $post = Post::find($id);
        $post->delete();
        return redirect()->back()->with('message', 'Date has been deleted');
    }

}

resources/views/dates/create.blade.php
@extends('layouts.backend')
@section('title')
{{ __(isset($post)?'Update post':'Create post') }}
@endsection
@section('content')
<div class="content">
    <div class="container-fluid">
        @if(session()->has('message'))
        <div class="alert alert-warning">
            {{ session()->get('message') }}
        </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="card card-light">
                    <div class="card-header with-border">
                        <h3 class="card-title"><i class="fa fa-edit"></i> {{ __(isset($post)?'Update Date':'Add Date') }}</h3>
                        <div class="card-tools float-right">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fa fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row pt-2">
                            <div class="col-12"><!--left col-->
                                <form action="@if(isset($post)) {{ route('dates.update', $post->id) }} @else {{ route('dates.store') }} @endif" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if(isset($post))
                                    @method('PUT')
                                    @endif
                                    @if(isset($post))
                                    <p class="alert alert-danger"><b>Date:</b>{{ $post->id }}</p>
                                    @endif
                                    <div class="form-group">
                                        <label for="note">Note</label>
                                        <input id="note" type="text" class="form-control" name="note" value="{{ $post->note ?? '' }}" placeholder="Note" title="Enter note" />
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="checkbox" class="form-check-input" name="status" value="1" @if(isset($post) && $post->status == 1) checked @endif>Closed
                                        </label>
                                    </div>
                                    <div class="form-group mt-3">
                                        <button class="btn btn-success btn-theme" type="submit">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dates/index.blade.php
@extends('layouts.backend')
@section('title')
{{ __('All Posts') }}
@endsection
@section('content')
<div class="content">
    <div class="container-fluid">
        @if(session()->has('message'))
        <div class="alert alert-warning">
            {{ session()->get('message') }}
        </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="card card-light">
                    <div class="card-header with-border">
                        <h3 class="card-title"><i class="fa fa-bell mr-1"></i> {{ __('All Dates') }}</h3>
                        <div class="card-tools float-right">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fa fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="dataTables" class="display nowrap" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Date</th>
                                    <th>Note</th>
                                    <th>Status</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->note }}</td>
                                    <td class="@if($post->status == 1) bg-danger @else bg-success @endif">{{ $post->status }}</td>
                                    <td><a href="{{ route('dates.edit', $post->id) }}" class="text-success fa fa-edit"></a></td>
                                    <td><a href="{{ route('dates.destroy', $post->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form').action = this.href; document.getElementById('delete-form').submit.click();" class="text-danger fa fa-trash"></button></td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Date</th>
                                    <th>Note</th>
                                    <th>Status</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('style')
<!-- dataTables plugin -->
<link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet" media="all"/>
<link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet" media="screen">
<link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet" media="all"/>
<!-- /dataTables plugin -->
@endsection
@section('script')
<!---dataTables plugin JavaScript -->
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="{{ asset('js/dataTables.js') }}"></script>
<!--/dataTables plugin JavaScript -->
@endsection

resources/views/dates/list.blade.php
@extends('layouts.backend')
@section('title')
{{ __('All Posts') }}
@endsection
@section('content')
<div class="content">
    <div class="container-fluid">
        @if(session()->has('message'))
        <div class="alert alert-warning">
            {{ session()->get('message') }}
        </div>
        @endif
        <div class="row">
            <div class="col-12">
                <div class="card card-light">
                    <div class="card-header with-border">
                        <h3 class="card-title"><i class="fa fa-bell mr-1"></i> {{ __('All Posts') }}</h3>
                        <div class="card-tools float-right">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fa fa-times"></i></button>
                        </div>
                    </div>
                    <div class="card-body">
                        <table id="dataTables" class="display nowrap" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Posted at</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->title }}</td>
                                    <td>{{ $post->created_at->format('jS M Y') }}</td>
                                    <td><a href="{{ route('blog.edit', $post->id) }}" class="text-success fa fa-edit"></a></td>
                                    <td><a href="{{ route('blog.destroy', $post->id) }}" onclick="event.preventDefault(); document.getElementById('delete-form').action = this.href; document.getElementById('delete-form').submit.click();" class="text-danger fa fa-trash"></button></td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Posted at</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('style')
<!-- dataTables plugin -->
<link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet" media="all"/>
<link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet" media="screen">
<link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet" media="all"/>
<!-- /dataTables plugin -->
@endsection
@section('script')
<!---dataTables plugin JavaScript -->
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.flash.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="{{ asset('js/dataTables.js') }}"></script>
<!--/dataTables plugin JavaScript -->
@endsection

resources/views/dates/show.blade.php
@extends('layouts.app')
@section('title')
{{ $post->title ?? '' }}
@endsection
@section('content')
<div class="container mx-auto min-h-screen">
    <div class="grid lg:grid-cols-[auto_1fr_auto] py-3">
        <div class="hidden lg:block">
            @include('layouts.info')
        </div>
        <div class="lg:px-3">
            <h1 class="text-3xl capitalize">{{  $post->title ?? '' }}</h1>
            <div class="mb-3">
                <p class="text-gray-500 text-sm">Posted at: {{ $post->created_at->format('jS M Y') }}</p>
            </div>
            <div class="mb-3">
                {{  $post->body ?? '' }}
            </div>
            @php
            $pathtofile = '/posts/'.$post->link;
            $info = pathinfo($pathtofile);
            @endphp
            @if (isset($info["extension"]) && $info["extension"] == "pdf")
                <object data="/posts/{{ $post->link }}" type="application/pdf" width="600" height="500" class="w-full overflow-hidden border-4">
                    <p class="bg-theme-light p-3 rounded"><a class="underline" href="/posts/{{ $post->link }}" download>{{ $post->title ?? 'Download' }}</a></p>
                    <embed src="/posts/{{ $post->link }}" width="100%" height="600px"/>
                </object>
            @else
                <img class="w-full" src="/posts/{{ $post->link }}" alt="{{ $post->title ?? '' }}" />
            @endif
        </div>
        <div class="hidden lg:block">
            @include('layouts.subject')
        </div>
    </div>
</div>
@endsection